# Generated by Django 6.0 on 2026-02-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0004_message_owner_subscriber_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата последней отправки"),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="next_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата следующей отправки"),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("once", "Однократно"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                ],
                default="once",
                max_length=20,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="newsletter.subscriber",
                verbose_name="Получатель",
            ),
        ),
        migrations.AddField(
            model_name="dispatchlog",
            name="trigger_type",
            field=models.CharField(
                choices=[("auto", "Автоматически"), ("manual", "Вручную")],
                default="auto",
                max_length=20,
                verbose_name="Тип запуска",
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                    ("paused", "Приостановлена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchlog",
            index=models.Index(fields=["dispatch", "status"], name="newsletter__dispatc_8f047a_idx"),
        ),
        migrations.AddIndex(
            model_name="dispatchlog",
            index=models.Index(fields=["attempt_time"], name="newsletter__attempt_976dd2_idx"),
        ),
    ]
